
import javax.swing.JOptionPane;
import sun.security.util.Password;
import java.io.*;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

public class Login extends javax.swing.JFrame {

    public static boolean status;
    /** Creates new form Login */
    public Login() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Validating User");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(null);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LOGIN HERE");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(160, 40, 70, 30);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("User Name");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(50, 100, 110, 30);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(50, 150, 100, 30);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(180, 100, 130, 30);

        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jPasswordField1);
        jPasswordField1.setBounds(180, 150, 130, 30);

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(140, 210, 120, 50);

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Login"));
        jPanel2.setLayout(null);
        jPanel1.add(jPanel2);
        jPanel2.setBounds(40, 70, 310, 130);

        jCheckBox1.setText("Admin Login");
        jPanel1.add(jCheckBox1);
        jCheckBox1.setBounds(290, 270, 100, 23);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        if (this.jCheckBox1.isSelected())
        {
           try{
               BufferedReader rdfile = new BufferedReader(new FileReader("login.txt"));
               String[] itemline = new String[100];
               String str;
               String uname=jTextField1.getText();
               char[] pwd=jPasswordField1.getPassword();
                String password=new String(pwd);                
                for (int x = 0; (str = rdfile.readLine()) != null; x++) {
                itemline[x] = str;
            }
                rdfile.close();
                String[] temp = itemline[0].split("\t");
                if((uname.equals(temp[0])&&(password.equals(temp[1])))){
               JOptionPane.showMessageDialog(null, "Admin Login Successfull");
               status=true;
               Inventory inv=new Inventory();
                inv.setVisible(true);
                
                this.setVisible(false);
           }
           else
           {
               JOptionPane.showMessageDialog(null, "Invalid User");
               jTextField1.setText(null);
               jPasswordField1.setText(null);
               jTextField1.requestFocus();
           }
           }
           catch(Exception e)
           {
               JOptionPane.showMessageDialog(null,e);
           }
           
        }
        else
        {
        try{
           String uname=jTextField1.getText();
           char[] pwd=jPasswordField1.getPassword();
           String password=new String(pwd);
           if((uname.equals("user")&&(password.equals("user2018")))){
               JOptionPane.showMessageDialog(null, "Login Successfull");
               status=false;
               Inventory inv=new Inventory();
                inv.setVisible(true);             
                this.setVisible(false);
           }
           else
           {
               JOptionPane.showMessageDialog(null, "Invalid User");
               jTextField1.setText(null);
               jPasswordField1.setText(null);
               jTextField1.requestFocus();
           }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
        jButton1ActionPerformed(evt);
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        
        Login lgn=new Login();
        lgn.setLocationRelativeTo(null);
        lgn.setVisible(true);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

}
