
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.*;

public class Splash extends javax.swing.JFrame {

    /** Creates new form Splash */
    public Splash() {
        initComponents();
        //jLabel1 = new JLabel(new ImageIcon(getClass().getResource("happiness-within.jpeg")));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        prog = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inventory_POS and BILLING");
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Serif", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 255, 255));
        jLabel2.setText("Loading ...");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(220, 140, 100, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackage/happiness-within.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 550, 300);

        prog.setBackground(new java.awt.Color(255, 255, 255));
        prog.setForeground(new java.awt.Color(255, 0, 0));
        prog.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(prog);
        prog.setBounds(0, 294, 550, 10);

        setSize(new java.awt.Dimension(566, 338));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

        public static void main(String args[]) throws InterruptedException {
       
        final Splash sp= new Splash();
        sp.setLocationRelativeTo(null);
        sp.setVisible(true);


    Thread th=new Thread() {
        public void run(){
        for(int i=1;i<=10;i++){
                    try {
                        Thread.sleep(500);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(Splash.class.getName()).log(Level.SEVERE, null, ex);
                    }
            if(i==1){sp.prog.setValue(10);}
            if(i==2){sp.prog.setValue(20);}
            if(i==3){sp.prog.setValue(30);}
            if(i==4){sp.prog.setValue(40);}
            if(i==5){sp.prog.setValue(50);}
            if(i==6){sp.prog.setValue(60);}
            if(i==7){sp.prog.setValue(70);}
            if(i==8){sp.prog.setValue(80);}
            if(i==9){sp.prog.setValue(90);}
            if(i==10){sp.prog.setValue(100);
            Login st=new Login();
            st.setVisible(true);
            sp.setVisible(false);}
                    
            
    }}
    };th.start();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JProgressBar prog;
    // End of variables declaration//GEN-END:variables

}
